language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install

env:
  global:
    - NODE_ENV=test

script:
  - npm test
after_success:
  - npm run coverage
  
dist: trusty

addons:
  sonarcloud:
    organization: "jjcaro98"
    token:
      secure: "1c920a2abeaed35b011f4e68929c3fdf1006fbea" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
